### ISSUE TITLE
Collaborate with conda-forge?

### ISSUE THREAD

**Issue by ngam** [tlc-pack/tlcpack#100]
Hi, we have pretty much all of what you publish on anaconda.org available through conda-forge. I am wondering if we could work together to minimize redundancy. Would you be interested in taking over/maintaining the packages on conda-forge?

I have just updated libtvm, tvm-py, etc. and it would be good to have you on board.

**Comment by ngam** [comment]
https://github.com/conda-forge/tvm-py-feedstock
https://github.com/conda-forge/libtvm-feedstock
...

**Comment by junrushao1994** [comment]
I'm very familiar with TVM build, but have to say I don't know much about conda. Happy to assist if you are interested!

**Comment by ngam** [comment]
That would be lovely. I can also get you up to speed with the conda ecosystem pretty quickly.
