### ISSUE TITLE
ci_hexagon image not being automatically validated

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#103]
When checking the images from our automated build today, it seems `ci_hexagon` is not being validated due to missing updates in https://github.com/tlc-pack/tlcpack/blob/main/jenkins/JenkinsFile-validate-docker-images.

Specifically, it would require updates in the parameter passing to the validation job:
https://github.com/tlc-pack/tlcpack/blob/c2aba3d3d3d0829fe3dd0d3b9264ca9a9b6d0c1c/jenkins/JenkinsFile-validate-docker-images#L115-L123

Also being added to the retagging and upload phase:
https://github.com/tlc-pack/tlcpack/blob/c2aba3d3d3d0829fe3dd0d3b9264ca9a9b6d0c1c/jenkins/JenkinsFile-validate-docker-images#L136-L156

cc @mehrdadh

**Comment by mehrdadh** [comment]
@leandron thanks for flagging this. I will send a follow up PR. I thought the jenkins file would run in pre-commit CI, no?

**Comment by leandron** [comment]
No we don’t have CI for the jenkinsfiles like this.

**Comment by leandron** [comment]
I checked this one, and the problem is now fixed. Thanks @mehrdadh!
