### ISSUE TITLE
Deprecate Python 3.6 build and packaging

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#107]
As noted many times, Python 3.6 is now EOL. Some of our dependencies such as TensorFlow don't even produce packages for this Python version anymore.

The proposal here is to disable Python 3.6 completely from our build and packaging in this repo.

cc @tqchen @areusch @driazati

**Comment by driazati** [comment]
agreed, https://github.com/apache/tvm/issues/9703 did this for TVM so it makes sense to mirror it here

**Comment by areusch** [comment]
+1

**Comment by leandron** [comment]
OK so I'll push this as a PR soon.
