### ISSUE TITLE
[RFC] Build images for CUDA 11 series

### ISSUE THREAD

**Issue by comaniac** [tlc-pack/tlcpack#120]
As CUDA 11 has been widely used, it would be better if the wheels also include CUDA 11 series. Although #70 has proposed to added CUDA 11.1, there's no follow-up in that issue for a month. Meanwhile, I'm hoping to have a release with CUDA 11.3 on my use cases. As a result, I'm proposing to add more CUDA 11 versions and getting rid of the oldest CUDA 10. For example, PyTorch now provides wheels for CUDA 10.2, 11.3 and 11.6.

Specifically, there are some plans in my mind:

* P1: 10.2, 11.3, 11.6.
    * Pro: This is the same version set as PyTorch.
    * Con: 1) If anyone rely on nightly build with CUDA 10.0 or 10.1 they may be upset. 2) I tested TVM with CUDA 11.3 without any issue, but not 11.6.
* P2: 10.0, 10.1, 10.2, 11.1, 11.3
    * Pro: Covered all requirements we've seen so far.
    * Cons: Longer build time.

Comments are welcome. @areusch @leandron @tqchen @shyam196

**Comment by areusch** [comment]
i'm also fine with any of those. our build time isn't horribly long right now, i think ~1h. do we want to any testing against CUDA in the nightly? i'm not sure we need that at this point, given it's a nightly; we can run the full test suite for releases.

**Comment by comaniac** [comment]
I just double checked the TVM CI and it's now using CUDA 11.0.3, so it might be better to also cover that. Combining the above comments, we could start from 10.2, 11.0, 11.1, 11.3. We can add 11.6 later.

If no objection I'll prepare a PR for docker files. Do we need to manually push the docker images for tlcpack?
