### ISSUE TITLE
[Release] Missing v0.10.dev0 is generating wrong dev version numbers

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#126]
After the release of v0.9.0, we'll need to find the *exact* point in the repository that should be tagged with the beginning of v0.10.dev0, so that the tooling in this repository can start producing the correct version numbers in the packages.

At the moment, we're still generating v0.9.devX versions, which are wrong.

The hash https://github.com/apache/tvm/commit/97b3076c3532f73a9d9eeba26a3f329f8e0f803d seems to be the latest one that  [v0.9.0](https://github.com/apache/tvm/commits/v0.9.0) and [main](https://github.com/apache/tvm/commits/main) have in common, so I wonder if https://github.com/apache/tvm/commit/0e23122846aa3b7a5350102d8c06fa21695d34be should be the one that marks the beginning of 0.10 development cycle.

Creating a tag is simple, but the main motivation I created this issue is to see whether our release guide should be amended to reflect the tagging of the beginning of next cycle to be done as part of the release process. What do others think?

cc @u99127 @areusch @u99127 @driazati @manupa-arm

**Comment by tqchen** [comment]
I agree we should document this in our release process

**Comment by driazati** [comment]
Yeah we shouldn't wait until a release next time to bump the version numbers, we should do them as soon as we do the release candidate branch cut, that way there's no gaps. At that point the only common commit will be the one before the branch cut since any further changes will be individually `cherry-pick`ed into the rc.

**Comment by tqchen** [comment]
I think in this case it is not about version number, but to create a tag v0.10.dev0 in the branching off pt when we cut off the release branch

**Comment by leandron** [comment]
OK, so in the interest of having the package being generated this Wednesday with the right name on PyPI, I'm planning to tag https://github.com/apache/tvm/commit/0e23122846aa3b7a5350102d8c06fa21695d34be with `v0.10.dev0`, while we discuss how the release guide should be amended.
