### ISSUE TITLE
Nightly build broke due to outdated CMake version

### ISSUE THREAD

**Issue by PhilippvK** [tlc-pack/tlcpack#138]
Since https://github.com/apache/tvm/commit/8c88aab77863e43985318c575a2fa648fc783338 TVM requires CMake version 3.18 or higher which led to failing CI jobs in the `tlcpack` repo. While the latest CMake version is installed into the containers (see `centos_install_cmake.sh`) the System version of CMake is used instead of the manually installed one.

To fix the CI up to 5 steps are required:
1. Update `centos_install_cmake.sh` to add the installed CMake version to the SYSTEM path. Alternative: build a specific version of CMake from source similarly to https://github.com/apache/tvm/blob/main/docker/install/ubuntu_install_cmake_source.sh
2. Build new Docker images using the fix
4. Tag a new version for the newly build images on Dockerhub (Optional if we just want to use the SHA1 of the latest image instead)
5. Update https://github.com/tlc-pack/tlcpack/blob/main/.github/workflows/wheel_manylinux_nightly.yaml#L20:L30 etc. to use the updated images

**Comment by driazati** [comment]
2 and 3 will happen automatically with https://github.com/tlc-pack/tlcpack/actions/runs/3275287205, so once that's done we can update the images in the workflows

**Comment by PhilippvK** [comment]
@driazati Should I then just use [tlcpack/package-cpu:bf872ef](https://hub.docker.com/layers/tlcpack/package-cpu/bf872ef/images/sha256-cbc11c625b44122bd73f67c3457f5ca3c24dd7812dce0a4aba506633a4b73ad0?context=explore) etc. or can we create a tag for this such as `v0.6`?

**Comment by driazati** [comment]
just the hash is probably fine, the version number doesn't add much meaning imo
