### ISSUE TITLE
[Release] Missing v0.11.dev0 is generating wrong dev version numbers

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#149]
As reported before in https://github.com/tlc-pack/tlcpack/issues/126 (for missing `v0.10.dev0`), we are missing `v0.11.dev0` in the repo, which is making the packages to be generated with the wrong version number. Today's package is wrongly marked still as `0.10.dev961`: https://pypi.org/project/apache-tvm/0.10.dev961/

In the interest of having packages generated with the right number, I identified https://github.com/apache/tvm/commit/fdc6894b7dae096d0ec983292aa0a2a475843f56 as the one that marks the beginning of `v0.11.dev0` cycle, so I'm marking that accordingly (context: the hash above is the first one that exists only in `main` and not in `v0.10.0`).

**Comment by leandron** [comment]
cc @driazati @AndrewZhaoLuo @tqchen @areusch

**Comment by leandron** [comment]
This is now created and visible at https://github.com/apache/tvm/tree/v0.11.dev0

**Comment by leandron** [comment]
I'll leave this issue open, just for visibility, but feel free to close it at any time if no further action/discussion is required.

**Comment by leandron** [comment]
I also deleted some incorrect packages generated in the meantime - 0.10.dev961, 0.10.dev948 and 0.10.dev911.

**Comment by leandron** [comment]
Closing this now, given there are no more actions.

**Comment by driazati** [comment]
@leandron I posted https://github.com/apache/tvm/pull/13351 to hopefully avoid this next time around, can you take a look?
