### ISSUE TITLE
CUDA wheel is borken

### ISSUE THREAD

**Issue by hsuanguo** [tlc-pack/tlcpack#2]
The cuda wheels don't really work, after installation, tvm package can be imported, however there will be CUDA error when ever try to call cuda runtime:

`CUDAError: Check failed: ret == 0 (-1 vs. 0) : cuModuleLoadData(&(module_[device_id]), data_.c_str()) failed with error: CUDA_ERROR_NOT_INITIALIZED`

to be more specific:

the wheels are borken after auditwheel repair:
https://github.com/tlc-pack/tlcpack/blob/master/scripts/build_tvm.sh#L114

The wheels before the repairing work just fine.

I didn't look into it, but I guess the issue is caused by packing cuda libraries into wheels, and is a bug from auditwheel.
Here in pytorch, the libraries are packed manually:
https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L192
and it mentions that auditwheel is kind of buggy.

**How to reproduce:**

- Install tvm using : pip install tlcpack-cu102-f https://tlcpack.ai/wheels.html 

- Test  with https://tvm.apache.org/docs/tutorials/get_started/relay_quick_start.html#sphx-glr-tutorials-get-started-relay-quick-start-py

- Then we should see the cuda error.

**Comment by tqchen** [comment]
The new cuda wheels for nightly are updated
