### ISSUE TITLE
How to build and package "master"?

### ISSUE THREAD

**Issue by mshawcroft** [tlc-pack/tlcpack#22]
Is there a mechanism available we can use to get these scripts to build and package master as opposed to the last release (in order to have nightly packaged builds) ?

**Comment by tqchen** [comment]
We already use github actions to build nightly for both conda and wheel(pending support for manylinux). See the scripts here https://github.com/tlc-pack/tlcpack/tree/main/.github/workflows

**Comment by tqchen** [comment]
let us know if you are interested in adding more target platforms(e.g. arm64, we might need qemu or an external runner though)

**Comment by mshawcroft** [comment]
arm native is interesting, longer term, in the short term, Im interested in how we can use this in house on internal branches that host material prior to upstreaming.

Where do the existing nightly whl packages of master get deployed to?

**Comment by tqchen** [comment]
They get deployed to a binary tag in the github via https://github.com/tlc-pack/tlcpack/blob/main/wheel/wheel_upload.py
https://github.com/tlc-pack/tlcpack/releases/tag/v0.7.dev1

Then https://github.com/tlc-pack/tlcpack/blob/main/wheel/wheel_prune_and_sync.py will synchronize the list of wheels to https://tlcpack.ai/wheels
