### ISSUE TITLE
Support Wheel Build from Stable Tag

### ISSUE THREAD

**Issue by mshawcroft** [tlc-pack/tlcpack#34]
The wheel download page currently offers a selection of various 0.7 and 0.8 dev builds, but there is no actual 0.7 release build.  What is the plan / time line to getting to the point that release builds are available here?

**Comment by tqchen** [comment]
see https://github.com/tlc-pack/tlcpack/blob/main/common/sync_package.py#L13

This is because the support for robust windows build comes after v0.7. So the actual dev tag is the closest we can get to a stable build for now. We will switch to v0.8 stable build once that is ready

**Comment by u99127** [comment]
Now that there is a v0.8 tag - could this be progressed ?

**Comment by tqchen** [comment]
Yes, sorry for the delayed reply. @leandron @areusch do you mind look into this? Thank you!

**Comment by tqchen** [comment]
bump a bit

**Comment by tqchen** [comment]
https://github.com/tlc-pack/tlcpack/pull/85
