### ISSUE TITLE
Wheel packages are generated with 'root' ownership

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#56]
When we use `build_wheel_manylinux.sh`, the resultant packages are generated with 'root' permission. This makes it a bit cumbersome to run cleanup tasks, as you end up with the need to run with "sudo" or root permissions.

I created this issue to check whether it would be interesting to something similar to https://github.com/apache/tvm/blob/main/docker/with_the_same_user.

cc @hogepodge @tqchen

**Comment by tqchen** [comment]
@leandron I think with the same user is interesting, however because we are using centos we need a different script, that is why I didn't do it in the first place
