### ISSUE TITLE
Incorrect TVM version reported by tlcpack

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#63]
When installing TVM via tlcpack, the version reported by that TVM should match with the version of the package. This is useful so that users know which version of TVM they have. It also makes things a bit weird on tvmc, which will rely on TVM (module) reporting the version correctly.

This is what I see:

```
$ pip list
Package         Version
--------------- ---------------------
attrs           21.2.0
cloudpickle     1.6.0
decorator       5.0.7
numpy           1.19.5
pip             21.1.1
pkg-resources   0.0.0
psutil          5.8.0
scipy           1.5.4
setuptools      56.2.0
synr            0.3
tlcpack-nightly 0.8.dev992+g76fb2afbf            <--- version of the package
tornado         6.1
wheel           0.36.2
$ python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
>>> tvm.__version__
'0.8.dev0'                                       <--- version of the module
>>> 

```

TVM has the `version.py` script (https://github.com/apache/tvm/blob/main/version.py), which supposedly updates the version in all the right places so that it is reported correctly. On tlcpack side, there is `sync_package.py` (https://github.com/tlc-pack/tlcpack/blob/main/common/sync_package.py), which does something similar, apart from the rebranding.

I tried checking where is that replacement missing, so that we can fix, but I was not successful.

@tqchen @icemelon any idea on where is this missing file that needs to be replaced?

**Comment by tqchen** [comment]
@leandron i think it is a matter of updating the sync_package file to update https://github.com/apache/tvm/blob/main/python/tvm/_ffi/libinfo.py#L223
