### ISSUE TITLE
Documentation on how to install tlcPack

### ISSUE THREAD

**Issue by WenheLI** [tlc-pack/tlcpack#7]
I am wondering if there is any documentation on how to install this via conda&pip?

**Comment by junrushao1994** [comment]
like this:
```
conda install -c tlcpack tlcpack-nightly       # cpu
conda install -c tlcpack tlcpack-nightly-cu100 # cuda 10.0
```

**Comment by WenheLI** [comment]
Thanks!
Is it possible to install it via pip?

**Comment by junrushao1994** [comment]
something like:
```
pip install tlcpack -f https://tlcpack.ai/wheels.html
```

**Comment by tqchen** [comment]
Right now the conda provides nightly(the lastet main artifacts) the pip nightly is still WIP

**Comment by tqchen** [comment]
As of now windows and mac nightly are added as 

```
pip install tlcpack-nightly -f https://tlcpack.ai/wheels
```

Linux pip is still WIP

**Comment by WenheLI** [comment]
@tqchen - Is anyone working on the linux pip? If not, I could try to help with it.

**Comment by tqchen** [comment]
cc @icemelon9

**Comment by tqchen** [comment]
https://tlcpack.ai/
