### ISSUE TITLE
Building images for CUDA 11

### ISSUE THREAD

**Issue by shyam196** [tlc-pack/tlcpack#70]
Thanks for building these packages -- it is a huge time saver!

Is there any interest in building packages for CUDA 11 series? I'm happy to look into this myself and upstream if you are keen :-)

**Comment by tqchen** [comment]
tHANKS @shyam196 , yes, indeed we would love to build cuda 11 series. cc @areusch  @leandron (we might want to also add the https://github.com/tlc-pack/tlcpack/tree/main/docker to nightly so it is easier to obtain the tlcpack building images)

**Comment by shyam196** [comment]
I'll take a look for you this week hopefully.

To clarify, is the rough procedure:

1. Add a new Dockerfile (extending pytorch/manylinux-cu111 for example)
2. Add CUDA 11 as an option in the relevant scripts / action matrix?

**Comment by DoTriN7** [comment]
Hi @shyam196, just to know, do you plan on building the packages for CUDA 11 soon? I would be so be a huge time saver as you said !
Best

**Comment by areusch** [comment]
@DoTriN7 we'll see if we can look at this in the next month or so

**Comment by areusch** [comment]
cc @hpanda-naut
