### ISSUE TITLE
tlcpack for Python 3.9

### ISSUE THREAD

**Issue by leandron** [tlc-pack/tlcpack#96]
Once the change I'm proposing in https://github.com/tlc-pack/tlcpack/pull/92 is merged, I'd like to suggest we start producing packages with Python 3.9 in the available images, which are all but `tlcpack/package-cu100`, that is updated only up to Python 3.8.

I'm mostly opening this issue for a discussion, as after #92 is merged, it should a pretty small patch.

@tqchen @areusch @Mousius any concerns?

**Comment by leandron** [comment]
Gentle ping as this is really a really low effort improvement we can do.

**Comment by tqchen** [comment]
I am supportive

**Comment by areusch** [comment]
i'm good with that

**Comment by junrushao1994** [comment]
Sounds great to me!

**Comment by leandron** [comment]
I renamed it to cover 3.9 for now. Will work on 3.10 later.

**Comment by leandron** [comment]
As we're now publishing linux wheels for python 3.6 to 3.10, I'll close this.
